export const env = {
  NODE_ENV: 'test',
  PORT: 5001,
  MONGO_URI: 'mongodb://localhost:27017/bip_test',
  JWT_ACCESS_SECRET: 'test_access_secret_minimum_64_characters_xxxxxxxxxxxxxxxxxxxxxxxxx',
  JWT_REFRESH_SECRET: 'test_refresh_secret_minimum_64_characters_xxxxxxxxxxxxxxxxxxxxxxxxx',
  JWT_ACCESS_EXPIRES: '15m',
  JWT_REFRESH_EXPIRES: '7d',
  SMTP_HOST: 'smtp.test.com',
  SMTP_PORT: 587,
  SMTP_USER: '',
  SMTP_PASS: '',
  FROM_EMAIL: 'noreply@test.com',
  FROM_NAME: 'Test',
  CLIENT_URL: 'http://localhost:3000',
  ANALYTICS_SERVICE_URL: 'http://localhost:8001',
  ANALYTICS_API_KEY: 'test-key',
  ANALYTICS_SERVICE_KEY: 'test-key',
  UPLOAD_DIR: './uploads',
  MAX_FILE_SIZE: 10485760,
  RATE_LIMIT_WINDOW: 15,
  RATE_LIMIT_MAX: 100,
  AUTH_RATE_LIMIT_MAX: 5,
  isProd: false,
  isDev: false,
};
